name: Terraform Plan
on:
  pull_request:
    branches: [main] # Run on PRs targeting any branch (e.g., main, set-up-google-cloud-infrastructure)
    types: [opened, synchronize, reopened]
jobs:
  terraform-plan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.5.0"
      - uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}
      - run: terraform init
      - run: terraform plan