name: Terraform Plan
on:
  pull_request:
    branches: [main] # Run on PRs targeting any branch (e.g., main, set-up-google-cloud-infrastructure)
    types: [opened, synchronize, reopened]
jobs:
  terraform-plan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.5.0"
      - uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}
      - run: terraform init
      - run: terraform plan -var="gcp_project_id=${{ secrets.GCP_PROJECT_ID }}" -var="db_password=${{ secrets.DB_PASSWORD }}"
      - name: Post Plan to PR
        if: always()
        uses: actions/github-script@v7
        with:
          script: |
            const planOutput = `${{ steps.terraform-plan.outputs.stdout }}`;
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `### Terraform Plan Output\n\`\`\`\n${planOutput}\n\`\`\``
            });