name: Terraform Plan

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]

jobs:
  terraform-plan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          path: root

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.5.0"

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure GCP Project
        run: |
          gcloud config set project ${{ secrets.GCP_PROJECT_ID }}
        working-directory: root/infra

      - name: Check directory contents
        run: ls -la ./infra || ls -la .
        working-directory: root

      - name: Initialize Terraform
        run: terraform init
        working-directory: root/infra

      - name: Validate Terraform Configuration
        run: terraform validate
        working-directory: root/infra

      - name: Generate Terraform Plan
        run: terraform plan -out=tfplan
        working-directory: root/infra

      - name: Post Terraform Plan to PR
        run: |
          terraform show -no-color tfplan > tfplan.txt
          gh pr comment --body-file tfplan.txt
        working-directory: root/infra
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}